development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:fef190f4298fce61fbb1701f1bc4622b@pike.redistogo.com:10706/
  channel_prefix: ZombieDice_production
